### ISSUE TITLE
Get to know Fisherman and entry added to the index heads up

### ISSUE THREAD

**Issue by ghost** [hasanozgan/theme-lambda#1]
Nice theme @hasanozgan!

I [added](https://github.com/fisherman/fisher-index/blob/master/INDEX#L39) **Lambda** to the [Fisherman](http://fisherman.sh) registry for you.

```
fisher install lambda
```

![jan 15 2016 09 27](https://cloud.githubusercontent.com/assets/8317250/12342078/377bc084-bb6a-11e5-9695-417805489b3c.gif)

In Fisherman, every plugin has meta data associated with like your username, plugin/theme description and variadic tags to help searching. Also, you don't need to create a PR directly in the Fisherman repo to add a new theme. 

One last thing, Fisherman is aware of index updates and manages itself automatically and independently, so users don't need to update the framework to know about the new theme, in this case Lambda.

Related:
- https://github.com/oh-my-fish/oh-my-fish/pull/234

**Comment by bucaran** [comment]
* https://github.com/oh-my-fish/oh-my-fish/pull/234

**Comment by fishequality** [comment]
oh-my-fish/oh-my-fish#234

**Comment by fishequality** [comment]
https://github.com/oh-my-fish/oh-my-fish/pull/234

**Comment by hasanozgan** [comment]
@bucaran thank you.
