### ISSUE TITLE
Function error?

### ISSUE THREAD

**Issue by SloppyPuppy** [hasanozgan/theme-lambda#24]
Context: fresh arch install, I've tried installing the theme on fisher and on oh my fish, same error. 

```
fish: Unknown command: hostname
~/.local/share/omf/themes/lambda/functions/fish_prompt.fish (line 1): 
hostname|cut -d . -f 1
^
in command substitution
        called on line 7 of file ~/.local/share/omf/themes/lambda/functions/fish_prompt.fish
in function 'fish_prompt'
in command substitution
~/.local/share/omf/themes/lambda/functions/fish_prompt.fish (line 7): Unknown command
    set -g __fish_prompt_hostname (hostname|cut -d . -f 1)
                                  ^
in function 'fish_prompt'
in command substitution

╰─λ 
```

**Comment by asy-init** [comment]
same

**Comment by asy-init** [comment]
@SloppyPuppy i dont think the theme supports the latest realease of fish shell i found ( in themes.md @ omf )

its called l yes its called l

heres a picture

![image](https://user-images.githubusercontent.com/94440862/146313171-2cb93892-3935-4dec-a5cc-cb70890c1d9a.png)

heres the github of l 

https://github.com/oh-my-fish/theme-l

**Comment by netologist** [comment]
Fixed
