### ISSUE TITLE
exit status on right prompt is not working

### ISSUE THREAD

**Issue by blu36iant** [hasanozgan/theme-lambda#4]
exit status at the right prompt always show 0 even if something goes wrong.
I guess it's because in the fish_right_prompt_ function you call the __tmux_prompt function before caching the $status of previous command.

I change order and it's working fine.

```
function fish_right_prompt
  set -l exit_code $status
  __tmux_promptthe
...
```

**Comment by bucaran** [comment]
@blu36iant I think this repo has been pretty much abandoned, just like oh-my-fish. I recommend upgrading to fisherman: https://github.com/fisherman/fisherman

**Comment by hasanozgan** [comment]
Thanks I will apply

**Comment by hasanozgan** [comment]
fixed
