### ISSUE TITLE
Not able to install theme-lambda with fisherman

### ISSUE THREAD

**Issue by tdhulster** [hasanozgan/theme-lambda#5]
It looks like the theme-lambda isn't registered in the Fisherman registry anymore.

When trying 
`fisher info` or `fisher ls-remote`
it doesn't return the theme-lambda

And when trying to installing it by 
`fisher i lambda` or `fisher i theme-lambda`
I get following error :
`Installing 1 plugin/s`
`! Fetch lambda github.com/fisherman/theme-lambda`
`! There was an error installing lambda or more plugin/s.`
`Try using a namespace before the plugin name: owner/lambda`

**Comment by ipatch** [comment]
@tdhulster I don't use `fisher` but I do use [omf](https://github.com/oh-my-fish/oh-my-fish) and have been using the lambda theme for quite some time now without a hitch.

**Comment by muhh** [comment]
Run into it myself and the fix is to run `fisher install hasanozgan/theme-lambda`.
